flaskr/home/routes.py
from flask import Blueprint, redirect, render_template, url_for, send_file, make_response, Response, session
from flask_login import current_user, login_required, logout_user
from flask import jsonify, request
from ..models import db, Stock
from . import graphs
from .. import ml_builder as ml
import os
import joblib
from .. import models

my_dict = {
    "Close": 1,
    "Open": 2,
    "High": 3,
    "Low": 4,
    "Volume": 5
}

# Blueprint Configuration
home_bp = Blueprint(
    'home_bp', __name__,
    template_folder='templates',
    static_folder='static'
)


@home_bp.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    # render homepage
    stocks = Stock.query.filter_by(user_id=current_user.get_id()).limit(5).all()
    if 'currId' in session:
        curr = session['currId'].upper()

    else:
        curr = ""
    return render_template(
        'dashboard.jinja2',
        title='Smart Trader',
        description='user homepage',
        template='dashboard',
        current_user=current_user,
        stocks=stocks,
        currTicker=curr,
        body=f'Welcome back to Smart Trader {current_user.username}'
    )


@home_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth_bp.login'))


@home_bp.route('/graph.png', methods=['GET', 'POST'])
@login_required
def graph():
    if request.method == 'POST':
        data = request.get_json()
        name = data['ticker']
        plot = data['plotType']
        data_vars = data['variables'][:2]
        variables = ""
        for variable in data_vars:
            variables += variable

        session['currId'] = name
        session['currPlot'] = plot
        session['currVariables'] = variables
        stock = Stock.query.filter_by(ticker=name).first()
        ticker = ml.get_ticker(stock.ticker, '1d')

        if f'{name}{plot}{variables}DataPng' not in session:
            if not data_vars:
                data_vars = None

            if stock is None:
                message = 'Please make sure to add a stock to the database with the add button before generating ' \
                          'graphs with the graph data button.'
            png_graph = graphs.get_graph(ticker, plot, data_vars)
            my_file = f'{name}{plot}{variables}DataPng'
            session[my_file] = my_file
            # current_path = os.path.abspath(os.getcwd())
            abs_path = os.path.abspath('flaskr/')
            path = f'{abs_path}home\\static\\dist\\images\\{my_file}.png'
            png_graph.savefig(path)

        message = []

        if data_vars:
            for data in data_vars:

                session[f'{name}{data}Mode'] = float(ticker[data].mode().min())
                session[f'{name}{data}Median'] = float(ticker[data].median().min())
                session[f'{name}{data}Mean'] = float(ticker[data].mean().min())

                message.append(my_dict[data])
                message.append(session[f'{name}{data}Mode'])
                message.append(session[f'{name}{data}Median'])
                message.append(session[f'{name}{data}Mean'])
        else:
            data = 'Close'
            session[f'{name}{data}Mode'] = float(ticker['Close'].mode().min())
            session[f'{name}{data}Median'] = float(ticker[data].median().min())
            session[f'{name}{data}Mean'] = float(ticker[data].mean().min())

            message.append(my_dict[data])
            message.append(session[f'{name}{data}Mode'])
            message.append(session[f'{name}{data}Median'])
            message.append(session[f'{name}{data}Mean'])

        message = jsonify(message)
        return message, 200

    else:
        name = ""
        plot = ""
        variables = ""

        if 'currId' in session:
            name = session['currId']
            plot = session['currPlot']
            variables = session['currVariables']

        if f'{name}{plot}{variables}DataPng' in session:
            abs_path = os.path.abspath('flaskr/')
            my_file = f'{name}{plot}{variables}DataPng'
            path = f'{abs_path}home\\static\\dist\\images\\{my_file}.png'
            return send_file(path, mimetype='image/png')

        else:
            stock = Stock.query.filter_by(user_id=current_user.get_id()).first()
            ticker = ml.get_ticker(stock.ticker, '1d')
            png_graph = graphs.get_graph(ticker)
            my_file = f'{stock.ticker}TickDataPng'
            session[my_file] = my_file
            abs_path = os.path.abspath('flaskr/')
            path = f'{abs_path}home\\static\\dist\\images\\{my_file}.png'
            png_graph.savefig(path)

        return graphs.format_graph(png_graph)


@home_bp.route('/addTicker', methods=['GET', 'POST'])
@login_required
def add_ticker():
    if request.method == 'POST':
        data = request.get_json()
        res = ml.get_ticker(data['stockName'], '1d')

        if res.empty:
            print("get ticker failed")
            return False

        else:
            fav = True if data['favSize'] < 5 else False
            stock = Stock.query.filter(Stock.ticker == data['stockName']).first()
            if stock is None:
                stock = Stock(
                    ticker=data['stockName'],
                    user_id=current_user.get_id(),
                    is_fav=fav
                )
            db.session.add(stock)
            db.session.commit()
        return 'OK', 200
    else:
        stocks = Stock.query.filter(Stock.user_id == current_user.get_id(), Stock.is_fav).all()

        return render_template(
            'dashboard.jinja2',
            title='Smart Trader',
            description='user homepage',
            template='dashboard',
            current_user=current_user,
            stocks=stocks
        )


@home_bp.route('/deleteTicker', methods=['GET', 'POST'])
@login_required
def delete_ticker():
    if request.method == 'POST':
        data = request.get_json()
        name = data['stockName']
        stock = Stock.query.filter(Stock.user_id == current_user.get_id(), Stock.ticker == name).delete()
        db.session.commit()
        abs_path = os.path.abspath('flaskr/')
        abs_path = f'{abs_path}home\\static\\dist\\images\\'
        imgs = os.listdir(abs_path)
        for img in imgs:
            if name in img:
                os.remove(f'{abs_path}{img}')
                temp = img.split('.')
                session.pop(temp[0], None)

        return 'OK', 200
    else:
        stocks = Stock.query.filter(Stock.user_id == current_user.get_id(), Stock.is_fav).all()

        return render_template(
            'dashboard.jinja2',
            title='Smart Trader',
            description='user homepage',
            template='dashboard',
            current_user=current_user,
            stocks=stocks
        )


@home_bp.route('/createModel', methods=['POST'])
@login_required
def create_model():
    if request.method == 'POST':
        data = request.get_json()
        name = data['stockName']
        my_file = f'{name}Model'
        if my_file not in session:
            ticker = ml.get_ticker(name, '1d')
            ml.drop_date_for_model(ticker)
            ticker_train, ticker_test = ml.train_test_split(ticker)
            vals = ml.train_and_test_model(ticker_train, ticker_test)
            # TODO uncomment
            # if isinstance(vals, str):
            # return 'model accuracy is insufficient with training set; adjust inputs.'
            abs_path = os.path.abspath('flaskr/')
            path = f'{abs_path}home\\static\\dist\\models\\{my_file}.pkl'
            joblib.dump(vals[0], path)
            model_data = models.ModelData(name, vals[0], vals[1], vals[2])
            score = vals[3]
            session[f'{name}ModelScore'] = score
            session[f'{name}ModelPrediction'] = ml.predict_price(name, vals[0])
            session[my_file] = path
            # create graph and store
            path = f'{abs_path}home\\static\\dist\\images\\{my_file}.png'
            session[f'{my_file}Graph'] = path
            model_graph = model_data.get_graph()
            model_graph.savefig(path)

    return 'OK', 200


@home_bp.route('/graphModel.png', methods=['GET', 'POST'])
@login_required
def graph_model():
    if request.method == 'POST':
        data = request.get_json()
        name = data['stockName']
        session['currModel'] = session[f'{name}Model']
        session['currModelGraph'] = session[f'{name}ModelGraph']
        # TODO print score in javascript
        if f'{name}ModelScore' in session:
            score = session[f'{name}ModelScore']
            res = {"score": score}
            res = jsonify(res)
            return res, 200

        return 'OK', 200

    else:
        if 'currModel' in session:
            path = session['currModelGraph']
            return send_file(path, mimetype='image/png')
        else:
            message = {"response": 'The model does not exists'}
            message = jsonify(message)
            return message


@home_bp.route('/getPrediction', methods=['GET', 'POST'])
@login_required
def get_prediction():
    if request.method == 'POST':
        data = request.get_json()
        name = data['stockName']
        my_file = f'{name}Model'
        session['currModelName'] = name
        return 'OK', 200
    else:
        if 'currModelName' in session:
            name = session['currModelName']
            prediction = session[f'{name}ModelPrediction']
            prediction_obj = {"prediction": prediction}
            prediction_json = jsonify(prediction_obj)
            return prediction_json
        else:
            message = {"message": "there is no prediction available. please create model first."}
            message = jsonify(message)
            return message


@home_bp.route('/search.png', methods=['GET', 'POST'])
@login_required
def search():
    if request.method == 'POST':
        data = request.get_json()

flaskr/home/templates/dashboard.jinja2
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
  <title>{{ title }}</title>
  <meta name="description" content="Smart Trader."/>
  <meta name="HandheldFriendly" content="True"/>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, viewport-fit=cover"/>
  <meta property="og:image:width" content="1000"/>
  <meta property="og:image:height" content="523"/>
  <meta name="theme-color" content="#5eb9d7"/>
    <link href="{{ url_for('static', filename='dist/css/dashboard.css') }}" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Poppins:200,300,500" rel="stylesheet"/>
  {% block pagestyles %}{% endblock %}
</head>

<body class="{{ template }}" onload="getGraph()">
<div id="main-container">
    <div id="sidebar-container">
        <h1 id="logo" class="side-item">Smart Trader</h1>
        <div id="sidebar-list" class="wrapper side-item">
            <h1>{{ current_user.username }}'s Stock List</h1>
            <ul id="stock-list">
                {% for stock in stocks %}
                    <li><a href="#" id="{{ stock.ticker }}" class="ticker"
                           onclick="sendPlotJson(this.id, true);return false;" >{{ stock.ticker.upper() }}</a></li>
                {% endfor %}
                {% block content %}{% endblock %}
            </ul>
            <div id="add-delete-container" class="two-elem">
                <button type="button" id="add-button" class="inner-item sidebar-button" onclick="addTicker()">Add</button>
                <button type="button'" id="delete-button" class="inner-item sidebar-button" onclick="deleteTicker()">Delete</button>
                <!--<button type="button'" id="search-button" class="inner-item sidebar-button" onclick="search()">Search</button>-->
                <!--<button type="button" id="fav-button" class="inner-item sidebar-button" onclick="favTicker()">Favorite</button>-->
            </div>
            <div id="logout-search-container" class="two-elem">
                <input type="text" id="search-bar" class="inner-item" placeholder="search...">
                <a href="{{ url_for('home_bp.logout') }}" id="logout" class="inner-item">Log out</a>
            </div>
        </div>
        <div id="data-controls" class="wrapper side-item">
            <h1>Historical Data Controls</h1>
            <div class="graph-button">
                    <button class="drop-button sidebar-button" onclick="sendPlotJson();return false">Graph Data</button>
            </div>
            <div id="checkbox">
                <p>Y Variables</p>
                <div id="check-row1" class="check-row">
                    <input type="checkbox" id="Volume" class="variables" name="volume" onclick="restrictVars(this.id)">
                    <label for="volume">volume</label><br>
                    <input type="checkbox" id="Open" class="variables" name="open" onclick="restrictVars(this.id)">
                    <label for="open">open</label>
                    <input type="checkbox" id="Close" class="variables" name="close" onclick="restrictVars(this.id)">
                    <label for="close">close</label>
                </div>
                <div id="check-row2" class="check-row">
                    <input type="checkbox" id="High" class="variables" name="high" onclick="restrictVars(this.id)">
                    <label for="high">high</label>
                    <input type="checkbox" id="Low" class="variables" name="low" onclick="restrictVars(this.id)">
                    <label for="low">low</label>
                </div>
            </div>
            <div id="checkbox">
                <p>Graph Type</p>
                <div id="check-row1" class="check-row">
                        <input type="checkbox" id="Tick" class="graph-types" name="Tick" onclick="restrict(this.id)">
                        <label for="Tick">Tick</label><br>
                        <input type="checkbox" id="Hist" class="graph-types" name="Hist" onclick="restrict(this.id)">
                        <label for="Hist">Hist</label>
                </div>
                <div id="check-row2" class="check-row">
                        <input type="checkbox" id="Scatter" class="graph-types" name="Scatter" onclick="restrict(this.id)">
                        <label for="Scatter">Scatter</label>
                        <!--<input type="checkbox" id="Pie" class="graph-types" name="Pie" onclick="restrict(this.id)">
                        <label for="Pie">Pie</label>-->
                </div>
            </div>
        </div>
        <div id="model-controls" class="wrapper side-item">
            <h1>Help</h1>
            <p>A.) To add/delete a ticker type it in the search box and click the appropriate button.
                The Stock list can display five stocks at a time.</p>
            <p>B.) Historical data can display a maximum of two Y variables at a time and Historical Data Controls will
            be applied to the ticker currently in the data visualizer.</p>
            <p>C.) Model controls consist of ("Create Model", "Display Model Efficacy", and "Predict Tomorrow's Price"</p>

        </div>
    </div>
    <div id="data-container" class="wrapper">
        <div class="pref">
            <h1 id="data-title">{{ currTicker }} Data Visualizer</h1>
            <button id="create-model" class="sidebar-button" onclick="createModel()">Create Model</button>
            <button id="compare-model" class="sidebar-button" onclick="graphModel()">Display Model Efficacy</button>
            <button id="predict-model" class="sidebar-button" onclick="predictPrice()">Predict Tomorrow's Price</button>
            <p id ="predicted-price" class="predicted-price"></p>
            <p id="model-score" class="model-score"></p>
            <p id="var1-mode" class="summ"></p>
            <p id="var1-median" class="summ"></p>
            <p id="var1-mean" class="summ"></p>
            <p id="var2-mode" class="summ"></p>
            <p id="var2-median" class="summ"></p>
            <p id="var2-mean" class="summ"></p>
        </div>
        <div id="data-visual-container">
            <img id="data-visual" src="" >
        </div>
    </div>
</div>
<script src="{{ url_for('static', filename='dist/js/main.min.js') }}"></script>
{% block additionalscripts %}{% endblock %}
</body>

</html>